# Generated by Django 4.2.1 on 2023-05-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('married', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dependents', models.IntegerField()),
                ('education', models.CharField(choices=[('graduate', 'Graduate'), ('notgraduate', 'Not Graduate')], max_length=12)),
                ('self_employed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('property_area', models.CharField(choices=[('rural', 'Rural'), ('semiurban', 'Semiurban'), ('urban', 'Urban')], max_length=9)),
                ('applicant_income', models.IntegerField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.FloatField()),
                ('credit_history', models.FloatField()),
                ('loan_status', models.BooleanField(default=False)),
            ],
        ),
    ]
