# Generated by Django 4.2.1 on 2023-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='dependents',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3+', '3+'), ('nan', 'Nan')], max_length=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nan', 'Nan')], max_length=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='married',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('nan', 'Nan')], max_length=3),
        ),
        migrations.AlterField(
            model_name='loan',
            name='self_employed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('nan', 'Nan')], max_length=3),
        ),
    ]
